all:
	g++ -std=c++17 -o ycsbTableCreate ycsbTableCreate.cpp -lcassandra
	g++ -std=c++17 -o connectionTest connectionTest.cpp -lcassandra
	g++ -std=c++17 -o insertData insertData.cpp -lcassandra
	g++ -std=c++17 -o dropkeyspace dropkeyspace.cpp -lcassandra
	g++ -std=c++17 -o readData readData.cpp -lcassandra
	g++ -std=c++17 -o readWriteTest readWriteTest.cpp -lcassandra